### ISSUE TITLE
你修改的stylishedit 2.0并未解决高亮模式下的问题

### ISSUE THREAD

**Issue by lychichem** [Firef0x/UserChrome#1]
机械合并y大的代码似乎不是个好选择，关于使脚本在高亮模式下正常工作的方法，黒仪大螃蟹在http://tieba.baidu.com/p/2541544018 的第67层楼中楼第二页已经说明，我不知道y大的修改部分起到了什么作用，至少我这里问题是没有解决的

**Comment by Firef0x** [comment]
@lychichem ，您好！

感谢提醒！最近比较少上贴吧，我没发现原来蟹神已经出手了。不过我按照帖子中的修改了以后， `stylish2.0_edit.uc.js` 只要点击 Stylish 编辑页面的 `Editor` 按钮，就会弹出一个警告窗口

```
Error_invalid_Editor_file
```

我查找了一下，应该是[这一行](https://github.com/Firef0x/UserChrome/blob/master/UserChromeJS/PteScript/stylish2.0_edit.uc.js#L324)弹出的。能帮忙找一下是什么原因吗？

`StylishCustom2_0.0.1.uc.js` 倒是没有问题。附上我作出的修改：
- [增加userChromeJS_Mix.xpi](https://github.com/Firef0x/UserChrome/commit/061f79f2f30e3e6697eeec3da92bf5336875055d)
- [完善stylish2.0_edit](https://github.com/Firef0x/UserChrome/commit/e12e92501613e17fd6db8113f19dd7c3484ee591)

此致！ :bow:

**Comment by lychichem** [comment]
不清楚，你是不是编辑器没有对temp的写入权限？看代码temp文件夹的权限没有的话应该是无法创建文件的，自然应该报错

**Comment by Firef0x** [comment]
我在 Windows 8 下测试的，编辑器用的是记事本，不存在权限不足的问题吧。

我等会新建个配置试试，你试试能不能用？

此致！ :bow:

**Comment by lychichem** [comment]
我是可以用的，我刚才试验了一下，可能与你指定的编辑器路径不正确有关。这个脚本似乎不能读取ucjs mix和addonpage的设置，编辑器路径的定义原版在第199行，格式应该是\前还有个\作为转义字符，而且program files的路径分别为progra~1（x86和x64上的program files）以及progra~2（x64上的program files （x86））

**Comment by Firef0x** [comment]
@lychichem ，您好！

感谢提醒！我这里终于正常了。我想现在已经完成了 `Stylish` 升级到 2.0 后的增强脚本升级工作：
- 原来使用 [stylish0.5_edit.uc.js](https://github.com/ywzhaiqi/userChromeJS/blob/master/stylishEdit/stylish0.5_edit.uc.js) 的，可以升级到 [stylish2.0_edit.uc.js](https://github.com/Firef0x/UserChrome/blob/master/UserChromeJS/PteScript/stylish2.0_edit.uc.js) 
- 原来使用 [StylishCustom.uc.js](http://pan.baidu.com/share/link?uk=2467242534&shareid=3781338190#path=%2F%5BUC%E8%84%9A%E6%9C%AC%5DStylishCustom) 的，可以升级到 [StylishCustom2.uc.js](https://github.com/Firef0x/UserChrome/blob/master/UserChromeJS/PteScript/StylishCustom2.uc.js)
- 原来使用 [userChromeJS_Mix.xpi](https://github.com/ywzhaiqi/userChromeJS/blob/master/userChromeJS_Mix.xpi/userChromeJS_Mix.xpi) 的，为了适应新版本 `Stylish` 使用标签页编辑，需要修改为 [userChromeJS_Mix.xpi](https://github.com/Firef0x/UserChrome/blob/master/Addons/userChromeJS_Mix.xpi/userChromeJS_Mix.xpi)

此致！ :bow:

**Comment by Firef0x** [comment]
@lychichem 上游已经解决了这个问题了，见 [stylish2.0_edit.uc.js, fix rich text mode issue](https://github.com/alice0775/userChrome.js/commit/0629cecf537367c45f0ec533b7ac6ca318df0881)
我想这个 Issue 终于可以关闭了。
